app/accounts/urls.py
from django.urls import path
from accounts.views import LoginView, logout_view, RegisterView, ProfileView


urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
    path('logout/', logout_view, name='logout')
]

app/api/urls.py
from django.urls import path, include
from rest_framework import routers
from api.views import ImageView

router = routers.DefaultRouter()
router.register('images', ImageView)
urlpatterns = [
    path('', include(router.urls)),
    path('image/<int:pk>/tofav/', ImageView.as_view({'get': 'image_favorite'})),
    path('image/<int:pk>/removefav/', ImageView.as_view({'get': 'image_remove_favorite'})),
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('webapp.urls')),
    path("auth/", include('accounts.urls')),
    path("api/", include('api.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/accounts/models.py
from django.db import models

# Create your models here.

app/webapp/models/images.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Image(models.Model):
    image = models.ImageField(
        verbose_name='Картинка',
        default='default_image.png',
        null=False,
        blank=False,
    )
    sign = models.CharField(
        verbose_name='Подпись',
        max_length=200,
        null=False,
        blank=False
    )
    author = models.CharField(verbose_name='Автор',
                              max_length=100,
                              null=False,
                              blank=False,
                              default='No name')
    users = models.ManyToManyField(
        to=User,
        related_name='images'
    )
    created_at = models.DateTimeField(
        verbose_name='Время создания',
        auto_now_add=True)
    updated_at = models.DateTimeField(
        verbose_name='Время изменения',
        auto_now=True)


    def __str__(self):
        return f"{self.image} - {self.sign}- {self.author}"



    class Meta:
        verbose_name = 'Картинка'
        verbose_name_plural = 'Картинки'

app/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class LoginForm(forms.Form):
    username = forms.CharField(required=True, label='Логин')
    password = forms.CharField(required=True, label='Пароль', widget=forms.PasswordInput)
    next = forms.CharField(required=False, widget=forms.HiddenInput)


class CustomUserCreationForm(forms.ModelForm):
    password = forms.CharField(label='Пароль', strip=False, required=True, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='Подтвердите пароль', strip=False, required=True, widget=forms.PasswordInput)


    class Meta:
        model = User
        fields = ('username', 'password', 'password_confirm', 'first_name', 'last_name', 'email',)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')
        if password and password_confirm and password != password_confirm:
            raise ValidationError('Пароли не совпадают')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get('password'))
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)


    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['password', 'password_confirm', 'old_password']

app/accounts/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.forms import LoginForm
from accounts.forms import CustomUserCreationForm, PasswordChangeForm
from accounts.forms import UserChangeForm

from webapp.models import Image


class LoginView(TemplateView):
    template_name = 'login.html'
    form = LoginForm

    def get(self, request, *args, **kwargs):
        next = request.GET.get('next')
        form_data = {} if not next else {'next': next}
        form = self.form(form_data)
        context = {'form': form}
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        if not form.is_valid():
            return redirect('login')
        username = form.cleaned_data.get('username')
        print(username)
        password = form.cleaned_data.get('password')
        next = form.cleaned_data.get('next')
        user = authenticate(request, username=username, password=password)
        print(user)
        if not user:
            return redirect('login')
        login(request, user)
        if next:
            return redirect(next)
        return redirect('index')


def logout_view(request):
    logout(request)
    return redirect('index')


class RegisterView(CreateView):
    template_name = 'register.html'
    form_class = CustomUserCreationForm
    success_url = '/'

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        context = {}
        context['form'] = form
        return self.render_to_response(context)


class ProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        images = Image.objects.filter(users=self.request.user)
        context['images'] = images
        return context

app/accounts/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
    <form action="{% url 'login' %}" method="POST">
        <div class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% bootstrap_button button_type="submit" content='Войти' %}
        </div>
    </form>

{% endblock %}

app/accounts/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
    <form action="{% url 'register' %}" method="POST">
    {% csrf_token %}
        <div class="form">
            {% bootstrap_form form %}
            {% bootstrap_button button_type="submit" content='Зарегистрироваться' %}
        </div>
    </form>

{% endblock %}

app/accounts/templates/user_change.html
{% extends 'base.html' %}
{% block title %}Редактировать пользователя{% endblock %}
{% block content %}
    <br>
    <br>
    <br>
    <br>
    <h1>Поменять личные данные</h1>

    <form action="{% url 'change' user_obj.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'partials/form.html' with form=form fields_only=True %}
        <br>
        <input class="btn btn-primary" type="submit" value="Сохранить">
    </form>

{% endblock %}

app/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% block title %}Пользователь{% endblock %}
{% block content %}
    <br>
<br>
<br>
<br>
    <h1>Личная страница пользователя {{ user_obj.username }}</h1>
    <p>Имя пользователя: {{ user_obj.username }}</p>
    <p>Имя: {{ user_obj.first_name }}</p>
    <p>Фамилия: {{ user_obj.last_name }}</p>
    <p>Почта: {{ user_obj.email }}</p>


    <h2 class="text-center clear"> Мои избранные фотки:</h2>
    <div class="row mt-5">
    {%for image in images%}
    <div class="col-sm-6">
          <div class="row no-gutters" >
            <div class="col-md-4">
              <img src="{{image.image.url}}" class="card-img" style="width:120px;height: 120px;" alt="">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">{{image.sign}}</h5>
                  <p>{{image.author}}</p>
                     <p>{{image.created_at}}</p>
                    <p>{{image.updated_at}}</p>
                  <div class="container">
                      <div class="row">
                          <div class="col-sm">
                           <a href="{% url 'image_detail' image.pk %}">Детально</a>
                        </div>
                         {% if request.user.is_authenticated%}
                          {% if request.user.username == image.author or perms.webapp.change_image%}
                        <div class="col-sm">
                           <a href="{% url 'image_edit' image.pk %}">Изменить</a>
                        </div>
                          {% endif %}
                          {% if request.user.username == image.author or perms.webapp.delete_image%}
                        <div class="col-sm">
                            <form action="{% url 'image_delete' image.pk %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-secondary btn-sm mr-5">Удалить</button>
                        </form>
                        </div>
                          {% endif %}

                           <div class="col-sm">
                                <form action="{% url 'image_favorite' image.pk %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-secondary btn-sm mr-5">Добавить в избранное</button>
                                </form>
                        </div>
                          <div class="col-sm">
                                <form action="{% url 'image_favorite' image.pk %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-secondary btn-sm mr-5">Удалить из избранного</button>
                                </form>
                        </div>
                          {% endif %}
                      </div>
                    </div>
              </div>
            </div>
          </div>
    </div>
    {%endfor%}

</div>




{% endblock %}

app/accounts/templates/user_password_change.html
{% extends 'base.html' %}
{% block title %}
Смена пароля
{% endblock %}

{% block content %}
    <h1>Смена пароля</h1>
    {% url 'password_change' user_obj.pk as action_url %}
    {% include 'partials/form.html' with action_url=action_url form_method="post" %}
{% endblock %}